// src/register/register.jsx
// /src/components/register.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import config from '../config';
import './register.css';

const Register = () => {
    const [email, setEmail] = useState('');
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [passwordconfirm, setPasswordconfirm] = useState('');
    const [message, setMessage] = useState('');
    const [isError, setIsError] = useState(false);
    const navigate = useNavigate();

    const validatePassword = (password) => {
        const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
        return passwordRegex.test(password);
    };

    const handleRegister = async (e) => {
        e.preventDefault();

        if (!validatePassword(password)) {
            setMessage('Password must be at least 8 characters long, include an uppercase letter, a lowercase letter, a number, and a special character.');
            setIsError(true);
            return;
        }

        if (password !== passwordconfirm) {
            setMessage("Passwords do not match.");
            setIsError(true);
            return;
        }

        try {
            const response = await axios.post(`${config.API_URL}/v1/register`, {
                email,
                username,
                password,
                passwordconfirm
            });

            if (response.data.success) {
                setMessage(response.data.message || 'User registered successfully');
                setIsError(false);
                
                try {
                    if (typeof window !== "undefined" && window.localStorage) {
                        localStorage.setItem('token', response.data.token);
                    } else {
                        console.warn("localStorage is not accessible.");
                    }
                } catch (storageError) {
                    console.error("localStorage access error:", storageError);
                    setMessage('Unable to save registration data locally.');
                    setIsError(true);
                    return;
                }

                setTimeout(() => navigate('/'), 1500);
            } else {
                setMessage(response.data.message || 'Registration failed.');
                setIsError(true);
            }
        } catch (error) {
            if (error.response && error.response.data && error.response.data.message) {
                setMessage(error.response.data.message);
            } else {
                setMessage('Something went wrong. Please try again.');
            }
            setIsError(true);
        }
    };

    return (
        <div className="register-container">
            <form className="register-form" onSubmit={handleRegister}>
                <h2 className="register-title">Create an Account</h2>
                
                <div className="input-container">
                    <label htmlFor="email">Email</label>
                    <input
                        type="email"
                        id="email"
                        name="email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        autoComplete="email"
                        placeholder="Enter your email"
                        required
                    />
                </div>

                <div className="input-container">
                    <label htmlFor="username">Username</label>
                    <input
                        type="text"
                        id="username"
                        name="username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        autoComplete="username"
                        placeholder="Choose a username"
                        required
                    />
                </div>

                <div className="input-container">
                    <label htmlFor="password">Password</label>
                    <input
                        type="password"
                        id="password"
                        name="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        autoComplete="new-password"
                        placeholder="Enter your password"
                        required
                    />
                </div>

                <div className="input-container">
                    <label htmlFor="passwordconfirm">Confirm Password</label>
                    <input
                        type="password"
                        id="passwordconfirm"
                        name="passwordconfirm"
                        value={passwordconfirm}
                        onChange={(e) => setPasswordconfirm(e.target.value)}
                        autoComplete="new-password"
                        placeholder="Confirm your password"
                        required
                    />
                </div>

                {message && (
                    <p className={isError ? 'error-message' : 'success-message'}>{message}</p>
                )}

                <button type="submit" className="register-button">Register</button>

                <div className="login-small-text">
                    <p>Already registered? <a href="/login" className="register-link">Log in</a></p>
                </div>
            </form>
        </div>
    );
};

export default Register;

// src/routes/register/+page.svelte
<script>
    import { writable } from 'svelte/store';

    const email = writable('');
    const password = writable('');
    const passwordConfirm = writable('');
    const username = writable('');
    const error = writable('');
    const success = writable('');

    const registerUser = async () => {
        error.set('');
        success.set('');

        const userData = {
            email: $email,
            password: $password,
            passwordConfirm: $passwordConfirm,
            username: $username
        };

        try {
            const response = await fetch('https://plevortapi.fryde.id.lv/v1/register', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(userData)
            });

            if (response.ok) {
                const data = await response.json();
                
                // Save the token to localStorage
                const token = data.token;
                localStorage.setItem('token', token);

                success.set(data.message || 'Registration successful!');

                // Redirect to homepage
                window.location.href = '/';
            } else {
                const data = await response.json();
                error.set(data.error || 'An unexpected error occurred.');
            }
        } catch (err) {
            console.error(err); // Log any errors
            error.set('Network error. Please try again later.');
        }
    };

    import './register.css'; 
</script>

<main>
    <div class="register-box">
        <form on:submit|preventDefault={registerUser}>
            <label for="email">Email</label>
            <input type="email" id="email" bind:value={$email} placeholder="e.g., example@domain.com" required />

            <label for="password">Password</label>
            <input type="password" id="password" bind:value={$password} placeholder="e.g., jSZ5?G23AKh7" required />

            <label for="passwordConfirm">Confirm Password</label>
            <input type="password" id="passwordConfirm" bind:value={$passwordConfirm} placeholder="e.g., jSZ5?G23AKh7" required />

            <label for="username">Username</label>
            <input type="text" id="username" bind:value={$username} placeholder="e.g., johndoe123" required />

            <label>
                <input type="checkbox" required /> I accept the <a href="/privacyandterms">Privacy Policy and TOS</a> 
                <p>if the TOS page looks weird please refresh it and there should be a white background. some bug</p>
            </label>
            
            <button type="submit">Register</button>

            {#if $error}
                <p class="error">Error: {$error}</p>
            {/if}
            {#if $success}
                <p class="success">Success: {$success}</p> 
            {/if}
        </form>

        <!-- Button to redirect to the login page -->
        <div class="login-redirect">
            <p>Already registered? </p>
            <button on:click={() => window.location.href = '../../login'}>
                Login
            </button>
        </div>
    </div>
</main>
