// src/login/login.jsx
// /src/components/Login.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import config from '../config';
import './login.css';

const Login = () => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [message, setMessage] = useState('');
    const [isError, setIsError] = useState(false);
    const navigate = useNavigate();

    const handleLogin = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post(`${config.API_URL}/v1/login`, 
                { email, password }, 
                {
                    validateStatus: (status) => status >= 200 && status < 300
                }
            );
            
            console.log("Response from server:", response);

            if (response.data.success) {
                setMessage(response.data.message);
                setIsError(false);
                localStorage.setItem('token', response.data.token);
                setTimeout(() => navigate('/'), 1500);
            } else {
                setMessage(response.data.message);
                setIsError(true);
            }
        } catch (error) {
            console.error("Error during login request:", error);
            
            setMessage('Something went wrong. Please try again.');
            setIsError(true);
        }
    };

    return (
        <div className="login-container">
            <form className="login-form" onSubmit={handleLogin}>
                <h2 className="login-title">Welcome Back</h2>
                <div className="input-container">
                    <label htmlFor="email">Email</label>
                    <input
                        type="email"
                        id="email"
                        name="email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        autoComplete="email"
                        placeholder="Enter your email"
                        required
                    />
                </div>
                <div className="input-container">
                    <label htmlFor="password">Password</label>
                    <input
                        type="password"
                        id="password"
                        name="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        autoComplete="current-password"
                        placeholder="Enter your password"
                        required
                    />
                </div>
                {message && (
                    <p className={isError ? 'error-message' : 'success-message'}>{message}</p>
                )}
                <button type="submit" className="login-button">Login</button>

                <div className="login-small-text">
                    <a href="/forgot-password" className="forgot-password">Forgot Password?</a>
                    <p>Don't have an account? <a href="/register" className="register-link">Register</a></p>
                </div>
            </form>
        </div>
    );
};

export default Login;

// src/routes/login/+page.svelte
<script>
    import { writable } from 'svelte/store';
    import './login.css'; // Import the CSS file

    const email = writable('');
    const password = writable('');
    const error = writable('');
    const success = writable('');

    const loginUser = async () => {
        error.set('');
        success.set('');

        const userData = {
            email: $email,
            password: $password
        };

        try {
            const response = await fetch('https://plevortapi.fryde.id.lv/v1/login', { 
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(userData)
            });

            if (response.ok) {
                const data = await response.json();
                
                // Save the token to localStorage
                const token = data.token;  
                localStorage.setItem('token', token);

                success.set(data.message || 'Login successful!');

                // Redirect to homepage
                window.location.href = '/';
            } else {
                const data = await response.json();
                error.set(data.error || 'An unexpected error occurred.');
            }
        } catch (err) {
            console.error(err);
            error.set('Network error. Please try again later.');
        }
    };
</script>

<main>
    <div class="login-box">
        <form on:submit|preventDefault={loginUser}>
            <label for="email">Email</label>
            <input type="email" id="email" bind:value={$email} placeholder="e.g., example@domain.com" required />

            <label for="password">Password</label>
            <input type="password" id="password" bind:value={$password} placeholder="e.g., jSZ5?G23AKh7" required />
            
            <button type="submit">Login</button>

            {#if $error}
                <p class="error">Error: {$error}</p>
            {/if}
            {#if $success}
                <p class="success">Success: {$success}</p>
            {/if}
        </form>

        <!-- Button to return to the register page -->
        <div class="register-redirect">
            <p>Don't have an account?</p>
            <button class="small-button" on:click={() => window.location.href = '/register'}>
                Return to Register
            </button>
        </div>
    </div>
</main>
